language: java
jdk:
  - oraclejdk8
sudo: false
env:
  global:
    - JVMCI_VERSION="jvmci-0.48"
    - JDK8_UPDATE_VERSION="172"
before_install: |
  nvm install 8
  if [ $TRAVIS_OS_NAME == "linux" ]; then
      JDK_TAR=${TRAVIS_BUILD_DIR}/../jdk.tar.gz
      wget https://github.com/graalvm/openjdk8-jvmci-builder/releases/download/${JVMCI_VERSION}/openjdk-8u${JDK8_UPDATE_VERSION}-${JVMCI_VERSION}-linux-amd64.tar.gz -O ${JDK_TAR}
      tar -C ${TRAVIS_BUILD_DIR}/.. -xzf ${JDK_TAR}
      export JVMCI_HOME=${TRAVIS_BUILD_DIR}/../openjdk1.8.0_${JDK8_UPDATE_VERSION}-${JVMCI_VERSION}
      
      # need to setup display for VSCode tests
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
      sleep 3
  fi

install:
  - npm install .
  - npm run compile

script:
  - npm test

