language: java
jdk:
  - oraclejdk8
sudo: false
before_install:
  - nvm install 6
script:
  - npm install .
  - npm run compile
  # - if [ "$TASK" = "checkstyle" ]; then ant checkstyle-jar && ant checkstyle; fi
