language: java
jdk:
  - oraclejdk8
sudo: false
before_install:
  - nvm install 8
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi

install:
  - npm install .
  - npm run compile

script:
  - npm test

